### ISSUE TITLE
[Question] How do I use it in Home Assistant?

### ISSUE THREAD

**Issue by Diegorro98** [MartinHjelmare/aiohomeconnect#33]
I wanted to test a little bit this new library at Home Assistant, but I don't have too much knowledge about how to implement it.

I have tried this at core's Home Connect component api.py file:
```python
class AsyncConfigEntryAuth(AbstractAuth):
    """Provide Home Connect authentication tied to an OAuth2 based config entry."""

    def __init__(
        self,
        hass: HomeAssistant,
        oauth_session: config_entry_oauth2_flow.OAuth2Session,
    ) -> None:
        """Initialize Home Connect Auth."""
        self.hass = hass
        super().__init__(oauth_session, host="https://simulator.home-connect.com")
        self.session = oauth_session

    async def async_get_access_token(self) -> str:
        """Return a valid access token."""
        await self.session.async_ensure_token_valid()

        return self.session.token
```
Then at `__init__.py` `async_setup_entry` method:
```python
from aiohomeconnect.client import Client as HomeConnectClient

async def async_setup_entry(hass: HomeAssistant, entry: HomeConnectConfigEntry) -> bool:
    # [...]
    session = config_entry_oauth2_flow.OAuth2Session(hass, entry, implementation)
    config_entry_auth = AsyncConfigEntryAuth(hass, session)
    home_connect = HomeConnectClient(config_entry_auth)
    return True
```
But because `OAuthSession2` doesn't have a `request` method (it has `async_request`) which is used at all the `Client` requests I found some troubles and I had to add the following method to the `AsyncConfigEntryAuth` class:
```python
    async def request(
        self, method: str, url: str, **kwargs: Any
    ) -> client.ClientResponse:
        """Make a request.

        The url parameter must start with a slash.
        """

        headers = kwargs.pop("headers", None)
        headers = {} if headers is None else dict(headers)
        headers = {key: val for key, val in headers.items() if val is not None}

        access_token = await self.async_get_access_token()
        headers["authorization"] = f"Bearer {access_token}"

        return await self.session.async_request(
            method,
            f"{self.host}/api{url}",
            **kwargs,
            headers=headers,
        )
```

Although it works because both, `aiohttp.client.ClientResponse` and `httpx.Response`, does have `json` method, I think this is too complex and breaks the strict typing (As requests return `aiohttp.client.ClientResponse` instead of `httpx.Response`)

### Additional info

I tried to create a question at discussions, but they are not enabled 😅

### Version

Any

### Platform

Debian 12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by MartinHjelmare** [comment]
> But because OAuthSession2 doesn't have a request method

Why does this matter?

You should not overwrite the `AbstractAuth.request` method.

**Comment by MartinHjelmare** [comment]
I see what you're doing wrong. The `AbstractAuth` accepts an httpx client as first parameter, not an `OAuthSession2` instance.

You can see an example of how to implement a client in the included CLI.

https://github.com/MartinHjelmare/aiohomeconnect/blob/main/src/aiohomeconnect/cli/client.py

**Comment by Diegorro98** [comment]
Sorry, I forgot about this issue.

Thank you for referring to the included API (it helped a lot in the PR development!).  

About how it should be integrated with Home Assistant, Is the following code right?
```python
class AsyncConfigEntryAuth(AbstractAuth):
    """Provide Home Connect authentication tied to an OAuth2 based config entry."""

    def __init__(
        self,
        hass: HomeAssistant,
        oauth_session: config_entry_oauth2_flow.OAuth2Session,
    ) -> None:
        """Initialize Home Connect Auth."""
        self.hass = hass
        super().__init__(
            get_async_client(hass), host=API_ENDPOINT
        )
        self.session = oauth_session

    async def async_get_access_token(self) -> str:
        """Return a valid access token."""
        await self.session.async_ensure_token_valid()

        return self.session.token
```
Or is there any other way to use httpx and oauth2 in Home Assistant?

**Comment by MartinHjelmare** [comment]
That looks correct.
